In [1]:
import numpy as np

In [2]:
# Q1

print(np.arange(24+1).reshape(5, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
# Q2

print(np.full((10, 10), 5))

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [4]:
# Q3

print(np.arange(0, 1, 0.125))

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]


In [5]:
# Q4

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 5, 4], [3, 2, 1]])

print(np.concatenate((x, y)))

[[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]


In [6]:
# Q5

A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a = int(len(A)/3)
b = 0
c = a
for i in range(a):
    print(A[b:c])
    b += a
    c += a

[1 2 3]
[4 5 6]
[7 8 9]
