In [1]:
# Q1
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(3, 4)
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype = float)
print(c.dtype)
print("Transpose of matrix\n", b.T)

float64
Transpose of matrix
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [2]:
# Q2
a = [1, 2, 3, 4, 5, 6]
b = np.array(a)
c = b.reshape(2, 3)
print(c.ndim)

c = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(c.ndim)

2
2


In [3]:
# Q3
a = np.arange(1, 13, 2).reshape(2, 3)
print(a)

[[ 1  3  5]
 [ 7  9 11]]


In [4]:
# Q4
# i
a = np.arange(1, 6)
b = np.arange(6, 11)
print(a + b)
print(a - b)
print(a**3 + b**3)
# ii

print(min(a))
print(max(b))
# iii

print(np.diff(a))
print(np.diff(b))
# iv

print(np.prod(a))
print(np.prod(b))
# v

print(np.mean(a))
print(np.mean(b))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 217  351  539  793 1125]
1
10
[1 1 1 1]
[1 1 1 1]
120
30240
3.0
8.0


In [5]:
# Q5
a = np.array([i**2 + 1 for i in range(1, 7)])
b = np.array([i**2 - 1 for i in range(1, 7)])
a.reshape(2, 3)
b.reshape(3, 2)
print(np.dot(a, b))

2269


In [6]:
# Q6
a = np.linspace(-3, 12, 12).reshape(3, 4)
print(a)

[[-3.         -1.63636364 -0.27272727  1.09090909]
 [ 2.45454545  3.81818182  5.18181818  6.54545455]
 [ 7.90909091  9.27272727 10.63636364 12.        ]]
