In [2]:
# Q1
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype = float)
print(a.ndim)
print(b.dtype)

1
float64


In [3]:
# Q2
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
b = a.reshape(2, 2, 2)
print(a.ndim)
print(b.ndim)
print(a)
print(b)

2
3
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
# Q3
a = np.array(["Arnab", "Sayan", "Souptick", "Debojit", "Suranjan"])
print(a.dtype)
print(a)

<U8
['Arnab' 'Sayan' 'Souptick' 'Debojit' 'Suranjan']


In [4]:
# Q4
a = np.arange(0, 5, 0.5)
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [7]:
# Q5
a = np.linspace(0, 5, 10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
