In [1]:
# Q1
import numpy as np

a, b, c = np.zeros(10, dtype = int), np.ones(10, dtype = int), np.full((10), 5)
print(np.concatenate((a, b, c)))

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


In [2]:
# Q2

a = np.array([i for i in range(30, 70+1) if i%2 == 0])
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [3]:
# Q3

a = np.random.random((15))
print(a)
print(np.average(a))

[0.93525558 0.77891947 0.78138708 0.72581581 0.49348525 0.12496833
 0.66793354 0.79330183 0.8754285  0.47053069 0.58862191 0.76385753
 0.18448902 0.88009137 0.63985777]
0.6469295770904043


In [4]:
# Q4

a = np.arange(15, 56)
def f(x):
    for i in range(len(x)-2):
        print(x[i+1])
print(f(a))

16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
None


In [5]:
# Q5

a = np.arange(10, 22).reshape(3, 4)
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [6]:
# Q6

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# Q7

a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [8]:
# Q8

print(np.diag([1, 2, 3, 4, 5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [9]:
# Q9

a = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])
print(a)
print("Sum of all elements:", np.sum(a))
print("Sum of each column:", np.sum(a, axis = 0))
print("Sum of each row:", np.sum(a, axis = 1))

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
Sum of all elements: 54
Sum of each column: [15 18 21]
Sum of each row: [ 6 18 30]


In [10]:
# Q10

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([10, 11, 12])
print("Original vector:\n", b)
print("\nOriginal matrix:\n", a)
c = np.empty_like(a)
for i in range(len(a)):
  c[i, :] = a[i, :] + b
print("\nAfter adding the vector b to each row of the matrix a:\n", c)

Original vector:
 [10 11 12]

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After adding the vector b to each row of the matrix a:
 [[11 13 15]
 [14 16 18]
 [17 19 21]]
